Cargo.lock, serde-generate/Cargo.toml, serde-generate/runtime/python/bincode/__init__.py, serde-generate/runtime/python/lcs/__init__.py, serde-generate/src/generate.rs, serde-generate/src/lib.rs, serde-generate/src/python3.rs, serde-generate/src/rust.rs, serde-generate/tests/installer.rs, serde-generate/tests/lcs_runtime.rs
Make available a python LCS runtime as part of Serde generate.
Included unit tests.
=> [serde generate] LCS runtime

serde-generate/src/generate.rs, serde-generate/src/python3.rs, serde-generate/tests/installer.rs
Add option to support python packages
included unit test
=> [serde generate] Support python packages

Cargo.lock, serde-generate/Cargo.toml, serde-generate/src/generate.rs, serde-generate/src/rust.rs, serde-generate/tests/installer.rs
Do not hard code version number for the generated Rust crate.
included test
=> [serde generate] improve CLI for Rust

Cargo.lock, serde-generate/Cargo.toml, serde-generate/src/rust.rs, serde-generate/tests/generation.rs
Following up with comments on https://github.com/libra/libra/pull/4830
CI
=> [serde generate] improve output of quote_container_definitions

Cargo.lock, serde-reflection/Cargo.toml, serde-reflection/README.md, serde-reflection/src/error.rs, serde-reflection/src/lib.rs, serde-reflection/tests/serde.rs
* Fix missing argument
* Add explanations
* Bump version for immediate release
builds
=> [serde-reflection] improve error messages

Cargo.lock, serde-generate/Cargo.toml, serde-generate/src/cpp.rs, serde-generate/src/indent.rs, serde-generate/src/java.rs, serde-generate/src/lib.rs, serde-generate/src/python3.rs, serde-generate/src/rust.rs, serde-generate/tests/generation.rs
* Support Java comments and external definitions (needed for "Move decoders" in Libra)
* Improve Rust codegen
* Final touch and going public with `indent` library
Included unit tests
=> [serde generate] new features for java + misc

serde-generate/src/golang.rs
Change the translation of "NewType" Serde containers (structs and variants) from
```
type Foo struct { Value uint64 }
```
into
```
type Foo uint64
```
This works for all unnamed types (primitive and anonymous constructions).
In the case of named types, we cannot simplify the codegen because the underlying type could be an interface, causing `Foo` to be also an interface.
unit tests
=> [serde generate] Go: simplify codegen for some `NewType` containers

serde-generate/src/golang.rs, serde-generate/src/java.rs
Add graceful handling of null values in the recommended APIs.
CI
=> [serde-generate] Java/Go: manage null values in (de)serialize helpers

serde-generate/runtime/java/com/novi/lcs/LcsTest.java, serde-generate/runtime/java/com/novi/serde/BinarySerializer.java, serde-generate/runtime/java/com/novi/serde/Bytes.java, serde-generate/runtime/java/com/novi/serde/Tuple2.java, serde-generate/runtime/java/com/novi/serde/Tuple3.java, serde-generate/runtime/java/com/novi/serde/Tuple4.java, serde-generate/runtime/java/com/novi/serde/Tuple5.java, serde-generate/runtime/java/com/novi/serde/Tuple6.java, serde-generate/src/java.rs
* Use proper exception to enforce argument invariants. (Only one "true" assert left.)
* Add missing invariants for `serialize_i128`
CI
=> [serde generate] fix Java invariants

Cargo.lock, serde-generate/Cargo.toml, serde-generate/src/config.rs, serde-generate/src/cpp.rs, serde-generate/src/golang.rs, serde-generate/src/indent.rs, serde-generate/src/java.rs, serde-generate/src/python3.rs, serde-generate/src/rust.rs, serde-generate/tests/cpp_generation.rs, serde-generate/tests/golang_generation.rs, serde-generate/tests/java_generation.rs, serde-generate/tests/python_generation.rs, serde-generate/tests/rust_generation.rs
Add option to inject custom code in various languages.
This is similar to comments, except inserted at the end of a class and without quotes.
unit test
=> [serde generate] add config option `custom_code`

serde-generate/README.md, serde-generate/runtime/cpp/binary.hpp, serde-generate/runtime/cpp/bincode.hpp, serde-generate/runtime/cpp/lcs.hpp, serde-generate/runtime/golang/bincode/deserializer.go, serde-generate/runtime/golang/bincode/serializer.go, serde-generate/runtime/golang/lcs/deserializer.go, serde-generate/runtime/golang/lcs/serializer.go, serde-generate/runtime/golang/serde/binary_deserializer.go, serde-generate/runtime/golang/serde/binary_serializer.go, serde-generate/runtime/java/com/novi/bincode/BincodeDeserializer.java, serde-generate/runtime/java/com/novi/bincode/BincodeSerializer.java, serde-generate/runtime/java/com/novi/lcs/LcsDeserializer.java, serde-generate/runtime/java/com/novi/lcs/LcsSerializer.java, serde-generate/runtime/java/com/novi/serde/BinaryDeserializer.java, serde-generate/runtime/java/com/novi/serde/BinarySerializer.java, serde-generate/src/golang.rs, serde-generate/src/lib.rs, serde-generate/src/test_utils.rs
Follow up with https://github.com/novifinancial/serde-reflection/issues/40 and add support for floats in all remaining bincode runtimes.
new test included
=> [serde-generate] Bincode floats

serde-generate/runtime/csharp/Serde.Tests/Serde.Tests.csproj
Revert last change to Serde.Tests.csproj
=> [serde-generate] fix CI for C#

.circleci/config.yml
* remove apt-get upgrade
* use debian packages for npm and node-js instead of nvm
```
node v10.23.1
npm 5.8.0
```
ci
=> [ci] simplify ci config

.circleci/config.yml
More simplifications for Go
ci
=> [Ci] update

Cargo.lock, serde-generate/Cargo.toml
Follow breaking change in textwrap 0.13.3
ci
=> [serde-generate] update textwrap

serde-generate/src/generate.rs
This argument is now named `--target-source-dir`
=> [serde-generate] Fix --target-source-dir required message

serde-generate/src/csharp.rs
`MemberwiseClone` is a private method on `object` which performs a shallow clone. Classes can choose to expose this to their users, and we should.
We may want to implement a deep clone which would take some extra work. This could be exposed as a separate `DeepClone` method.
=> CSharp: Add Clone methods

Cargo.lock, serde-generate/Cargo.toml, serde-generate/README.md, serde-generate/src/lib.rs, serde-name/Cargo.toml, serde-reflection/Cargo.toml, serde-reflection/README.md, serde-reflection/src/lib.rs
Improve documentation of serde-reflection and serde-generate to address common questions.
CI
=> [serde-reflection/generate] improve documentation

.circleci/config.yml, Cargo.lock, serde-generate/Cargo.toml, serde-generate/README.md, serde-generate/src/lib.rs
Update CI and docs after #106
CI
=> [serde-generated] update ci and docs after #106

Cargo.lock, serde-generate/Cargo.toml, serde-generate/README.md, serde-generate/runtime/dart/bcs/bcs_serializer.dart, serde-generate/runtime/typescript/bcs/bcsDeserializer.ts, serde-generate/runtime/typescript/bcs/bcsSerializer.ts, serde-generate/src/lib.rs
=> [serde-generate] update doc + prepare release

.circleci/config.yml, serde-generate/runtime/swift/Package.swift, serde-generate/runtime/swift/Tests/LinuxMain.swift, serde-generate/runtime/swift/Tests/SerdeTests/XCTestManifests.swift
=> Add missing license headers
