novifinancial/serde-reflection

- serde-reflection/README.md
- serde-reflection/src/de.rs
- serde-reflection/src/lib.rs
- serde-reflection/tests/serde.rs
`trace_type` was assuming that we find the variants of an enum starting with index 0. However, this doesn't need to be the case if we use trace_value first.
The new code is not making assumptions on the tracing state any longer. In the worst case, it may have to scan indexes to find a new variant, but the normal case is still O(1).
Also improve the documentation while we're at it.
See new targeted unit test
> [serde reflection] fix interaction between trace_value and trace_type in enums

- Cargo.lock
- serde-reflection/Cargo.toml
- serde-reflection/README.md
- serde-reflection/src/de.rs
- serde-reflection/src/format.rs
- serde-reflection/src/lib.rs
- serde-reflection/src/ser.rs
- serde-reflection/src/trace.rs
- serde-reflection/tests/format.rs
- serde-reflection/tests/serde.rs
This PR aims to address #5 by introducing a more powerful unification algorithm with proper variables and term-sharing.
included unit tests
> [serde-reflection] support recursive types

- Cargo.lock
- Cargo.toml
- README.md
- serde-name/Cargo.toml
- serde-name/README.md
- serde-name/README.tpl
- serde-name/src/lib.rs
- serde-name/tests/serde_name.rs
The goal of this crate is to provide a minimal library that can be used at runtime for cryptographic use cases (e.g. seeding hash functions in a predictable way).
```
cargo test
```
> [serde-name] New minimal library to extract serde names

- serde-reflection/src/de.rs
- serde-reflection/src/error.rs
- serde-reflection/src/lib.rs
- serde-reflection/src/trace.rs
What I'm trying to do with serde-reflection (providing a proc-macro alternative to generate `ContainerFormat`) does not work if the key of BTreeMap has to be `'static`.
> Use String rather than &'static str in Registry

- Cargo.lock
- serde-generate/Cargo.toml
- serde-generate/README.md
- serde-generate/src/analyzer.rs
- serde-generate/src/generate.rs
- serde-generate/src/lib.rs
- serde-generate/src/rust.rs
- serde-generate/tests/analyzer.rs
- serde-generate/tests/generation.rs
- serde-generate/tests/runtime.rs
* Generate Rust code from the Serde format. (One possible use case is for documentation)
* End-to-end to verify interoperability using bincode encoding.
```
cargo test
cargo run -p serde-generate -- --language rust <(curl https://raw.githubusercontent.com/libra/libra/master/testsuite/generate-format/tests/staged/libra.yaml)
```
> [serde generate] add support for rust

- Cargo.lock
- serde-generate/Cargo.toml
- serde-generate/src/generate.rs
- serde-generate/src/lib.rs
- serde-generate/src/python3.rs
- serde-generate/src/rust.rs
- serde-generate/tests/installer.rs
* Use `include_str!` to embed serde types and the bincode runtime of python into `serdegen`.
* Add options to control how to install a rust crate or python modules for the generated code and the embedded runtimes.
new unit tests
```
cargo run -p serde-generate -- --with-runtimes serde bincode --name libra_types --target-source-dir ../testing --language python3 <(curl https://raw.githubusercontent.com/libra/libra/master/testsuite/generate-format/tests/staged/libra.yaml) &&
(cd ../testing && python3 -c 'import libra_types as lt; import bincode; help(lt.Transaction)')
```
> [serde generate] Add options to install module and runtime(s)

- .circleci/config.yml
- Cargo.lock
- serde-generate/Cargo.toml
- serde-generate/README.md
- serde-generate/runtime/cpp/bincode.hpp
- serde-generate/runtime/cpp/lcs.hpp
- serde-generate/runtime/cpp/serde.hpp
- serde-generate/src/cpp.rs
- serde-generate/src/generate.rs
- serde-generate/src/lib.rs
- serde-generate/src/python3.rs
- serde-generate/tests/bincode_runtime.rs
- serde-generate/tests/generation.rs
- serde-generate/tests/installer.rs
- serde-generate/tests/lcs_runtime.rs
- serde-generate/tests/runtime.rs
* Code generation for C++ containers
* bincode runtime tested against the Rust implementation
* LCS runtime tested against the [Rust implementation of the Libra repository](https://github.com/libra/libra/tree/master/common/lcs)
* Code installer (check out `cargo run -p serde-generate -- --help` for options)
To minimize the amount of generated, I chose to use "Traits" and a number of C++17 features (or std library additions). The generated code and the runtimes have no dependencies outside c++ stdlib and can be deployed as headers.
Code sharing between bincode and LCS do not require complex "visiting" APIs similar to serde/Rust. However, maps were a bit tricky because LCS requires a strict ordering of keys.
```
cargo test
cargo run -p serde-generate -- --language Cpp <(curl …
```
> [Serde generate] Code generation, bincode runtime, and LCS runtime for C++

- .circleci/config.yml
- Cargo.lock
- serde-generate/Cargo.toml
- serde-generate/README.md
- serde-generate/runtime/java/serde/Deserializer.java
- serde-generate/runtime/java/serde/FixedLength.java
- serde-generate/runtime/java/serde/Int128.java
- serde-generate/runtime/java/serde/Serializer.java
- serde-generate/runtime/java/serde/Tuple2.java
- serde-generate/runtime/java/serde/Tuple3.java
- serde-generate/runtime/java/serde/Tuple4.java
- serde-generate/runtime/java/serde/Tuple5.java
- serde-generate/runtime/java/serde/Tuple6.java
- serde-generate/runtime/java/serde/Unsigned.java
- serde-generate/src/generate.rs
- serde-generate/src/java.rs
- serde-generate/src/lib.rs
- serde-generate/tests/bincode_runtime.rs
- serde-generate/tests/generation.rs
- serde-generate/tests/installer.rs
- serde-generate/tests/lcs_runtime.rs
Add code generation for Java
* Class definitions
* Serializer and Deserializer interfaces (minimal APIs for now)
* Serialization and Deserialization methods, including name mangling and helper functions for anonymous types.
Serialization runtimes for LCS and bincode (and e2e tests) will be added next.
Notes:
* We are not using any fancy feature such as reflection or template programming so it should be pretty easy to make this approach work for many other languages.
* I used Java type annotations to fill the gaps in Java type system but obviously it is not enforcing anything by itself.
```
cargo run -p serde-generate -- --module-name Test --language Java <(curl https://raw.githubusercontent.com/libra/libra/master/testsuite/generate-format/tests/staged/consensus.yaml)
cargo run -p …
```
> [serde generate] Add code generation for Java

- serde-generate/runtime/java/serde/ArrayLen.java
- serde-generate/runtime/java/serde/Deserializer.java
- serde-generate/runtime/java/serde/Serializer.java
- serde-generate/runtime/java/serde/Tuple2.java
- serde-generate/runtime/java/serde/Tuple3.java
- serde-generate/runtime/java/serde/Tuple4.java
- serde-generate/runtime/java/serde/Tuple5.java
- serde-generate/runtime/java/serde/Tuple6.java
- serde-generate/src/java.rs
- serde-generate/src/test_utils.rs
Following up with #23 and improving code generation to prepare Libra transaction builders and bincode/LCS runtime implementations.
* Make annotations look more similar to existing Java annotations (e.g. `ArrayLen`)
* Use byte[] for bytes, (Array)List for sequences, (Hash)Map for maps 
* Implement Java traits `equals` and `hashCode`
* Reduce imports and use long names to minimize risks of name collisions
* Better code sharing
Unit tests
> [serde generate] Improve java code generation

- Cargo.lock
- serde-generate/Cargo.toml
- serde-generate/runtime/cpp/lcs.hpp
- serde-generate/src/test_utils.rs
A piece of logic was missing in the C++ class for LCS serialization.
This affected serialization (and LCS-based hashing) of strings and sequences of length > 127 (and incidentally enums with this many variants).
I added a new test case using large strings and large byte-sequences.
> [c++] fix bug in LCS serialization of sequences

- Cargo.lock
- serde-generate/Cargo.toml
- serde-generate/runtime/java/com/facebook/serde/BinaryDeserializer.java
- serde-generate/runtime/python/bincode/__init__.py
- serde-generate/runtime/python/lcs/__init__.py
- serde-generate/src/analyzer.rs
- serde-generate/src/lib.rs
- serde-generate/src/rust.rs
- serde-generate/tests/bincode_runtime.rs
- serde-generate/tests/generation.rs
- serde-generate/tests/lcs_runtime.rs
This is a first attempt in Rust only to support two more use cases:
* Although serde-reflection does not extract comments, we may obtain some by other means: allow injecting them.
* Sometimes we wish to generate classes that refer to definitions from another YAML.
existing and new unit tests
> [Serde generate] add APIs to support comments and external dependencies in Rust

- serde-generate/src/cpp.rs
- serde-generate/src/indent.rs
- serde-generate/src/java.rs
- serde-generate/src/python3.rs
- serde-generate/src/rust.rs
* Refactor the code to introduce a shared state in each language and avoid long lists of parameters in codegen functions
* Use new library https://github.com/facebookincubator/serde-reflection/pull/31 for indenting code.
unit tests + inspect outputs for each language with
```
cargo run -p serde-generate -- --module-name Libra --language rust <(curl https://raw.githubusercontent.com/libra/libra/master/testsuite/generate-format/tests/staged/consensus.yaml)  | less
```
> [serde generate] cleanup code-generation

- Cargo.lock
- serde-generate/Cargo.toml
- serde-generate/README.md
- serde-generate/src/lib.rs
- serde-generate/src/python3.rs
- serde-generate/tests/cli.rs
- serde-generate/tests/generation.rs
* Fix formatting of comments
* omit INDEX and VARIANTS when serialization is skipped
* (possibly breaking) set `# pyre-strict` in generated code
include unit tests + test in Libra
> [Serde generate] improve python codegen

- .circleci/config.yml
- serde-generate/Cargo.toml
- serde-generate/README.md
- serde-generate/runtime/golang/src/serde/interfaces.go
- serde-generate/runtime/golang/src/serde/types.go
- serde-generate/src/generate.rs
- serde-generate/src/golang.rs
- serde-generate/src/java.rs
- serde-generate/src/lib.rs
- serde-generate/tests/generation.rs
* Add code generation in Go.
* Add support for Go in CI
* Generated code relies on abstract interfaces for (de)serialization (to be implemented separately in https://github.com/facebookincubator/serde-reflection/issues/42).
The main design decision was whether to use reflection (as in python) or generate helpers (as in Java). I chose the latter because the result is more type-safe and should compile to faster code. It should not be too hard to make the generated code reflection-friendly later, if needed.
included unit test
> [Serde generate] initial support for golang

- serde-generate/runtime/cpp/binary.hpp
- serde-generate/runtime/cpp/bincode.hpp
- serde-generate/runtime/cpp/lcs.hpp
Share code between Bincode and LCS. This is similar to what we do in Java but in the spirit of C++, we use the [CRTP](https://en.wikipedia.org/wiki/Curiously_recurring_template_pattern) instead of virtual method calls.
existing tests
> [serde generate] c++ runtime: share code between bincode and LCS

- serde-generate/runtime/golang/lcs/serializer.go
- serde-generate/tests/runtimes.rs
Broken change added in my previous diff at last min, because runtime golang tests was not run with build.
This diff adds the test and fix the lcs serializer.
cargo test -p serde-generate --test golang_generation
> add golang runtime tests into build; fix lcs serializer

- serde-generate/src/common.rs
- serde-generate/src/config.rs
- serde-generate/src/cpp.rs
- serde-generate/src/generate.rs
- serde-generate/src/golang.rs
- serde-generate/src/java.rs
- serde-generate/src/lib.rs
- serde-generate/src/python3.rs
- serde-generate/tests/golang_generation.rs
- serde-generate/tests/runtimes.rs
Many small fixes and improvements. Notably in the recent Go codegen:
* fix external definitions (adding missing imports)
* fix field names that were still in small caps (hence private)
* make `Installer` usable: now create a subdirectory for the package and a file `lib.go`
* remove the latest call-by-pointer (Serialize) => turns out this simplifies greatly enums (making `Enum__Variant` an `Enum` instead of `&Enum__Variant`)
unit tests + used in my next libra PR
> [Serde generate] various fixes in codegen

- Cargo.lock
- serde-generate/Cargo.toml
- serde-generate/src/golang.rs
- serde-generate/tests/golang_generation.rs
Sadly, there is no way to disable the warning "unused import" in Go and it's fatal.
Combined with the fact that imports are mandatory (no alternatives with a fully qualified name), this is a bummer but anyways I made it work.
included unit tests
> [serde generate] fix fatal warning in Go

- Cargo.lock
- serde-generate/Cargo.toml
- serde-generate/src/golang.rs
Per popular demand, we are reverting 89c5f4eb5b59 to avoid copying data while passing container values as arguments. The goal is to use pointers consistently where one would have used `const&` in C++ or `&` Rust.
Also, changing `isBla` to take a pointer receiver so that type-ckecking in user code is not affected when switching `config.serialization` on and off.
unit test
> [Serde generate] Go: pass structs by pointer

- serde-generate/runtime/golang/lcs/deserializer.go
- serde-generate/runtime/golang/lcs/lcs_test.go
- serde-generate/runtime/golang/lcs/serializer.go
- serde-generate/src/golang.rs
- serde-generate/tests/runtimes.rs
* Support LCS maps
* This makes it possible to use the same testing suite as other languages (covering all LCS types). 
* Fix deserialization of option types
* Add missing LcsSerialize on enums
unit tests
> [serde generate] Go: LCS maps + fixes

- Cargo.lock
- serde-generate/Cargo.toml
- serde-generate/README.md
- serde-generate/runtime/golang/bincode/deserializer.go
- serde-generate/runtime/golang/bincode/serializer.go
- serde-generate/runtime/golang/lcs/deserializer.go
- serde-generate/runtime/golang/lcs/lcs_test.go
- serde-generate/runtime/golang/lcs/serializer.go
- serde-generate/runtime/golang/serde/binary_deserializer.go
- serde-generate/runtime/golang/serde/binary_serializer.go
- serde-generate/src/lib.rs
- serde-generate/tests/golang_generation.rs
- serde-generate/tests/runtimes.rs
* Provide a bincode runtime in Go.
* The code is largely shared with LCS, following other language implementations.
* This tentatively concludes the work on adding Go to serde-generate.
unit test
> [serde-generate] Go: bincode runtime

- serde-generate/runtime/java/com/novi/serde/Bytes.java
* Make the default constructor non-copying (does not prevent sharing but faster)
* Create convenient safe APIs `Bytes.empty()` and `Bytes.valueOf(content)`
CI
> [serde generate] java runtime: improve Bytes class

- serde-generate/runtime/python/bincode/__init__.py
- serde-generate/runtime/python/bincode/test_bincode.py
- serde-generate/runtime/python/lcs/__init__.py
- serde-generate/runtime/python/lcs/test_lcs.py
- serde-generate/runtime/python/serde_binary/__init__.py
* Make the python runtime look more similar to the other implementations by creating proper `*Serializer` classes.
* In particular, we use fixed input/output buffers (owned by the (de)serializer) instead of concatenating/copying bytes.
* Reflection (the python-specific part) happens in the methods `(de)serialize_any`.
* For now, I created one layer of abstract class (`BinarySerializer`) instead of two (`BinarySerializer` + `Serializer`) to avoid creating more packages. (Still need to figure out a packaging strategy)
Quick testing suggests serialization is about 20% faster now and deserialization of long sequences up to 30X faster.
CI
> [serde generate] refactor python runtime

- serde-generate/src/lib.rs
- serde-generate/src/python3.rs
- serde-generate/tests/python_runtime.rs
Generate dataclass definitions with `frozen=True`
* This will make hashing available for more complex datatypes (hence dictionaries -- aka. Serde maps)
* This could also come handy in the future (e.g. to enforce value invariants in a post_init method).
CI
> [serde generate] python: switch to "frozen" dataclasses

- serde-generate/runtime/python/bincode/__init__.py
- serde-generate/runtime/python/bincode/test_bincode.py
- serde-generate/runtime/python/serde_binary/__init__.py
Let's follow the Rust implementation of `bincode` and add support for floats (in the IEEE 754 format, little endian).
In this PR, we start with python.
unit test
> [serde generate] add floats to Python bincode runtime

- Cargo.lock
- serde-generate/Cargo.toml
- serde-generate/src/test_utils.rs
- serde-generate/tests/cpp_runtime.rs
- serde-generate/tests/golang_runtime.rs
- serde-generate/tests/java_runtime.rs
- serde-generate/tests/python_runtime.rs
- serde-generate/tests/rust_runtime.rs
- serde-name/Cargo.toml
- serde-reflection/Cargo.toml
Libra-Canonical-Serialization (LCS) is now available as a crate so we don't need to (conditionally) pull `libra.git` for testing.
CI
> [serde generate] switch to LCS crate + remove feature "runtime-testing"

- serde-generate/runtime/typescript/serde/binaryDeserializer.ts
- serde-generate/runtime/typescript/serde/binarySerializer.ts
- Update typescript runtime to use `util` for `TextEncoder`/`TextDecoder`
- Return null for Unit (instead of undefined)
- Handle more than double space needed for a new byte array insert (`ensureBufferWillHandleSize`)
no change
> Update binary serde

- serde-generate/runtime/csharp/Bcs/Bcs.csproj
- serde-generate/runtime/csharp/Bincode/Bincode.csproj
- serde-generate/runtime/csharp/Serde/Serde.csproj
- serde-generate/src/csharp.rs
```
Class library (C#)
Author: Microsoft
Description: A project for creating a class library that targets .NET Standard or .NET Core
Options:
-f|--framework  The target framework for the project.
netcoreapp3.1     - Target netcoreapp3.1
netstandard2.1    - Target netstandard2.1
netstandard2.0    - Target netstandard2.0
Default: netstandard2.0
```
The current framework default for .NET class libraries is netstandard2.0. Update to reflect that.
Visual
> Update class lib TargetFramework .NET project attr to current default

- Cargo.lock
- serde-generate/Cargo.toml
- serde-generate/README.md
- serde-generate/src/lib.rs
* Includes latest config changes for C#
* Python runtime requires numpy >= 1.20.1 for typechecking with Pyre
CI
> [serde-generate] release version 0.19.0

- Cargo.lock
- serde-generate/Cargo.toml
- serde-generate/src/typescript.rs
- serde-generate/tests/typescript_generation.rs
Prior to change, external namespaces were pull in as a single type script file:
```
workspace/diem/shuffle/move/examples/main/txn_builders/diemTypes.ts
```
To better comply with deno conventions, this has been updated to namespace/mod.ts:
```
workspace/diem/shuffle/move/examples/main/txn_builders/diemTypes/mod.ts
```
`cargo test test_typescript_code_compiles_with_external_definitions`
> Typescript external definitions use mod.ts

- Cargo.lock
- serde-generate/Cargo.toml
- serde-generate/src/typescript.rs
- serde-generate/tests/typescript_runtime.rs
Previously, custom external code did not abide by mod.ts convention.
Prior:
```
import * as DiemTypes from ../diemTypes/index.ts
```
```
import * as DiemTypes from ../diemTypes/mod.ts
```
cargo test
> [serde-generate] Make typescript source installer follow mod.ts convention

- serde-generate/README.md
- serde-generate/runtime/dart/pubspec.yaml
- serde-generate/runtime/dart/test/bcs_test.dart
- serde-generate/runtime/dart/test/bincode_test.dart
- serde-generate/runtime/dart/test/serde_test.dart
- serde-generate/src/lib.rs
- serde-generate/tests/dart_runtime.rs
This is me trying to make the basic Dart unit tests runnable from the CLI.
```
cd serde-generate/runtime/dart
dart test
```
> [dart] make `dart test` work from runtime/dart

- Cargo.lock
- serde-generate/Cargo.toml
- serde-generate/runtime/python/serde_binary/__init__.py
- serde-generate/src/python3.rs
- serde-generate/src/swift.rs
- serde-generate/src/test_utils.rs
- serde-generate/tests/dart_runtime.rs
Support `enum Foo { Bar(), Baz{} }`
new test cases + CI
> [serde-generate] fix empty struct/tuple variants in python and swift
